version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  scraper:
    build: ./scraper
    volumes:
      - ./data:/app/data
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JOB_TITLES=${JOB_TITLES}
      - LOCATION=${LOCATION}
      - TIME_FILTER=${TIME_FILTER}
      - NUM_PAGES=${NUM_PAGES}
      - MAX_JOBS=${MAX_JOBS}
      - OUTPUT_DIR=/app/data
      - OUTPUT_FILENAME=${OUTPUT_FILENAME}
    restart: "no"
    profiles: [jobs]
    
  loader:
    build: ./loader
    volumes:
      - ./data:/app/data
    depends_on:
      - scraper
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: "no"
    profiles: [jobs]

  api:
    build: ./api
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - loader
    environment:
      - DATABASE_URL=${DATABASE_URL}

  web-ui:
    build: ./web-ui
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data: