version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  scraper:
    build: ./scraper
    volumes:
      - ./data:/app/data
    restart: "no"  # Run once and exit

  transformer:
    build: ./transformer
    volumes:
      - ./data:/app/data
    depends_on:
      - scraper
    restart: "no"  # Run once and exit

  loader:
    build: ./loader
    volumes:
      - ./data:/app/data
    depends_on:
      - transformer
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: "no"

  api:
    build: ./api
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - loader
    environment:
      - DATABASE_URL=${DATABASE_URL}

  web-ui:
    build: ./web-ui
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data: